weather-api/mp-rest/url=https://api.openweathermap.org
weather-api/mp-rest/scope=javax.inject.Singleton
weather-api/mp-rest/apikey=5c51ced207188772616e9d6b901dfce3

quarkus.mongodb.database=users




#%test.quarkus.devservices.enabled=false
quarkus.devservices.enabled=true
quarkus.datasource.devservices.image-name=postgres:14
quarkus.datasource.devservices.port=5432
%test.quarkus.datasource.devservices.port=5435



quarkus.hibernate-orm.database.generation=update

quarkus.test.integration-test-profile=test
