name: CI/CD
on:
  push:
    branches: [main, develop, 'feat/**']
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: roachseb/code-haven/.github/workflows/devsecops.yml@main
    secrets: inherit